name: build nightly deb

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: download ipa
      run: |
       wget https://nightly.link/Uckermark/not-a-bypass/workflows/main/main/not-a-bypass.zip?h=f0629a50cb35e5d42891f511bc0fec0188e28ae4
       unzip 'not-a-bypass.zip?h=f0629a50cb35e5d42891f511bc0fec0188e28ae4'
       unzip 'Not a bypass.ipa'
    - name: pack deb package
      run: ./build_nightly_deb.sh
    - name: Upload deb
      uses: actions/upload-artifact@v3
      with:
       name: not-a-bypass-nightly-deb
       path: not-a-bypass-nightly.deb
