name: build

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
     - uses: actions/checkout@v3
     - name: Install Dependecies
       run: brew install ldid
     - name: Compile
       run: make
     - name: pack deb package
       run: ./build_nightly_deb.sh
     - name: Upload deb
       uses: actions/upload-artifact@v3
       with:
        name: not-a-bypass
        path: |
         packages/Not a bypass.ipa
         not-a-bypass.deb
